version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # 改为3000端口
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./secrets/Mikoshi.env
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
    depends_on:
      - db-init

  db-init:
    build: ./backend
    command: ["python", "init_db.py"]
    env_file:
      - ./secrets/Mikoshi.env
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: