version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "10000:10000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app  # For live reload during development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Keep node_modules isolated
    depends_on:
      - backend